// Copyright (c) 2018 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//   IBM Corporation
:projectid: microprofile-fault_tolerance
:page-layout: guide
:page-duration: 15-20 minutes
:page-releasedate: 2018-02-12
:page-description: Learn how to use MicroProfile Fault Tolerance to enable applications to function even when one of the microservices is unavailable.
:page-tags: ['REST', 'MicroProfile', 'microservices', 'Fault Tolerance', '@Retry', '@Fallback']
:page-permalink: /guides/{projectid}
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
:source-highlighter: prettify
= Handling failures with Fault Tolerance

Learn how to use MicroProfile Fault Tolerance to enable applications to function 
even when one of the microservices is unavailable.

// =================================================================================================
// What you'll learn
// =================================================================================================

== What you'll learn
You will learn how to build fault tolerant microservices so that you can reduce the impact from failure and 
ensure continued operation of services.
You will use the `@Retry` and `@Fallback` methods to define a criteria on when to retry and to provide an 
alternative solution for a failed execution.
Fault Tolerance enables the applications to function even when one of the services is unavailable, 
making service invocation more resilient.

// =================================================================================================
// Getting Started
// =================================================================================================

include::{common-includes}/gitclone.adoc[]


// =================================================================================================
// Try what you'll build
// =================================================================================================

=== Try what you'll build

The `finish` directory in the root of this guide contains the finished
JWT security implementation for the services in the application. Feel free to give it a try before you proceed with building your own.

To try out the application, first navigate to the `finish` directory and then execute the following
Maven goals to build the application and run it inside Open Liberty:

```
mvn clean install
mvn liberty:start-server

```

Point your browser to the `http://localhost:9080/inventory/systems` URL. This is the starting point of the 
inventory service and it displays the current contents of the inventory. As you might expect, these are 
empty since nothing is stored in the inventory yet. Next, point your browser to the 
`http://localhost:9080/inventory/systems/localhost` URL. You see a result in JSON format with the system 
properties of your local JVM. When you visit this URL, these system properties are automatically stored 
in the inventory. Go back to `http://localhost:9080/inventory/systems` and you see a new entry for localhost. 
For simplicity, only the OS name and username are shown here for each host. You can repeat this process for 
your own hostname or any other machine that is running the system service.

Now navigate to the `CustomConfigProperties.json` file in the `finish` directory and change the property 
`io_openliberty_guides_system_inMaintenance` from false to true and save the file. There is no need to 
restart the server.Now return to your browser and point back to the 
`http://localhost:9080/inventory/systems/localhost` URL. You will now see the cached properties from 
systems for this localhost due to the system service now being in maintanence.

Once you are done checking out the application, stop the Open Liberty server:

```
mvn liberty:stop-server
```

Now, navigate back to the `start` directory to begin.
Proceed with the following two sections to add MicroProfile JWT to the back-end and basic app security to the front-end.





// =================================================================================================
// Why use MP Fault Tolerance?
// =================================================================================================
=== Why use MP Fault Tolerance?
It is becoming increasingly important to build fault tolerant microservices and MicroProfile (MP) 
Fault Tolerance provides a simple and flexible solution.
Fault tolerance is about leveraging different strategies to guide the execution and result of some logic.
Retry policies, bulkheads, and circuit breakers are popular concepts in this area. 
They dictate whether and when executions should take place, and fallbacks offer an alternative result 
when an execution does not complete successfully.

MP Fault Tolerance offers the following Fault Tolerance policies:

* Timeout: Define a duration for timeout

* Retry: Define a criteria on when to retry

* Fallback: provide an alternative solution for a failed execution

* CircuitBreaker: offer a way of fail fast by automatically failing execution to prevent the system 
overloading and indefinite wait or timeout by the clients

* Bulkhead: isolate failures in part of the system while the rest part of the system can still function

In this guide we will be focusing on `@Retry` and `@Fallback`.
[source, java, indent=0, role="no_copy"]

// =================================================================================================
// Enabling Fault Tolerance into the application
// =================================================================================================
== Enabling Fault Tolerance into the application

Begin by navigating to the `pom.xml` file to check the required dependency. The microprofile-fault-tolerance-api 
dependency has been added for you in the start/pom.xml file. This feature allows you to use the MicroProfile 
Fault Tolerance API to build fault tolerant microservices.

The mpFaultTolerance-1.0 feature has also been enabled in the `start/src/main/liberty/config/server.xml` file.

Now that the MicroProfile Fault Tolerance feature has been enabled, the application's fallback mechanism needs 
to be set up.

For ease of use, the two microservice being run in this application are being "served up" 
by the same server.
This means that one cannot be taken down without the other.
To overcome this challenge, we will imitate the HTTP responses and Exceptions that would normally be 
executed when a server cannot be reached due to the server being taken down maintenance. Taking the server
up and down dynamically will be done in this guide using dynamic configuration using MP config. If you want 
to learn more about setting up dynamic configuration, see `Configuring Microprofile with MP Config`.

Create the System Resource class in `start/src/main/java/io/openliberty/guides/system/SystemResource.java`:

[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/system/SystemResource.java[tags=503_response]
----
This file retrieves all of the system properties and returns them as a JSON Object.
The `getProperties()` method in this class has been modified for this fault tolerance guide so that 
if the config property `io_openliberty_guides_system_inMaintenance` from the 
`CustomConfigProperties.json` file is assigned the value of false, a json object containing the system 
properties is returned. However, if this config property is assigned a value of true, then a 503 HTTP 
response is returned to the browser and a message is returned to the terminal to let the developer 
know that the service is down.

This 503 HTTP response needs to be recognised and acted upon by the other microservice of our application 
(Inventory). To do this, navigate to `start/src/main/java/io/openliberty/guides/inventory/client/SystemClient.java`
to create the System Client class:

[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/inventory/SystemClient.java[tags=throw_IOException]
----
This class is a Client for the system service.

In this class there is a method called `setStaus()`. This method returns a boolean based on whether a 200 
response is returned by the system service. If a 200 is returned, the method returns true. However if the response 
is anything other than 200, then false is returned. In this guide, a new if statement has been added to the 
method that checks to see if the response is specifically a 503 response. A 503 HTTP response is returned if the 
server being called is unable to handle the request due to a temporary overload or scheduled maintenance, which 
would likely be alleviated after some delay). If the response is 503, an IOException is thrown. This type of 
exception is thrown when an input or output operation is failed or interpreted.

This `setStatus()` method is called by the public `isResponseOk()` method which is used in 
`InventoryManager.java`.

// =================================================================================================
// Adding the @Retry and @Fallback annotations
// =================================================================================================
=== Adding the @Retry and @Fallback annotations

Now that our inventory microservice is able to recognise that the system microservice has been taken 
down for maintenance through the 503 HTTP response retruned as a result and has thrown an IOException 
as a result of this microservice being in maintanence, a fallback method needs to be set out.
Navigate to `start/src/main/io/openliberty/guides/inventory/InventoryManager.java` to create the 
Inventory Manager class:

[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/inventory/InventoryManager.java[tags=add_retry_fallback]
----

The `@Retry` annotation specified here dictates on what conditions to retry establishing the connection 
to the system service (i.e. on an IOException) and how many times it should be retried (i.e. 3 times).
The `@Fallback` annotation specified dictates which method to call when the reties are unsuccessful 
(in this case use the fallbackForGet method).

The `fallbackForGet()` method that has been added as the designated fallback method for the original `get()` 
method, checks to see if the properties variable is null. If the properties variable is null, this suggests 
that the application has not been able to successfully reach the system service to get the system's 
properties previously, thus the method simply prints out a json warning message in the browser. However, if 
the properties variable is not null, this method retruns a json of the cached property values to the browser.


Next navigate to `start/src/main/java/io/openliberty/guides/inventory/InventoryResource.java` to create the 
Inventory Resource class:

[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/inventory/InventoryResource.java[tags=fault_tolerance]
----

The if statement in this class now returns an error message when the inventory service is down for maintanence 
and calls the `get()` method in the InventoryManager.java class when the inventory service is up and running 
as normal.
All references to the email configuration property have been removed from this file.

The application has now been sucessfully set up to be fault tolerant.


// =================================================================================================
// Building the application
// =================================================================================================

include::{common-includes}/mvnbuild.adoc[]


// =================================================================================================
// Starting the application
// =================================================================================================

== Starting the application

To see the new application in action, run the Maven `liberty:start-server` command from the `start` 
directory:

[source]
----
$ mvn liberty:start-server
----

Once the server is running, you can test the fault tolerance of the application by dynamically changing 
the `io_openliberty_guides_system_inMaintenance` value in the `CustomConfigProperties.json` file. This 
property will be set to true at first, but change it to false and save the file and your changes will be 
added dynamically, there is no need to reset the server (this is dynamic config). If you want more information 
on how these dynamic configuration properties were set up please visit the "Configuring Microservices" guide 
on the OpenLiberty website. Simply refresh the page now to see the dynamic changes.

Change the value back to true to see the cached version of the properties.


// =================================================================================================
// Testing the application
// =================================================================================================

== Testing the application

While you can test your application manually, you should rely on automated tests since they will trigger a 
failure whenever a code change introduces a defect. Since the application is a RESTful web service application, 
you can use JUnit and the RESTful web service Client API to write tests. In testing the functionality of the 
application, the scopes and dependencies are being tested.

Create `FaultToleranceTest.java` class in `start/src/test/java/it/io/openliberty/guides/faulttolerance/` and add 
the following code:

[source, java, indent=0]
----
link:finish/src/test/java/it/io/openliberty/guides/faulttolerance/FaultToleranceTest.java[tags=ft_testing]
----

The `@BeforeClass` annotation is placed on a method that executes before any of the test cases. In this case, 
the `oneTimeSetup()` method retrieves the port number for the Open Liberty server and builds a base URL string 
that is used throughout the tests.

The `@Before` and `@After` annotations are placed on methods that execute before and after every test case. These 
methods are generally used to perform any setup and teardown tasks. In this case, the setup method creates a 
JAX-RS client which makes HTTP requests to the inventory service. This client must also be registered with a 
JSON-P provider (JsrJsonpProvider) to process JSON resources. The teardown method simply destroys this client 
instance as well as the HTTP responses, resets the changed configuration file and the retry counter.

Let’s break down the test cases:

* `testFallbackForGet()` sends a request to `inventory` service to get the systems properties for a 
hostname, when `system` service is avialable. Then, it puts the `system` service on maintenance. After that, 
it makes a second request to `inventory` service to return the system properties for that hostname. 
Lastly, it asserts if the system properties returned from the first request were more than the second time. 

** In the second request, the fallback method from `inventory` service was called to return the cached properties. However for the first request, the `inventory` service returned the properties from making a connection to `system` service.

* `testRetryGettingSystemProperties()` sends a request to `inventory` service to try to get the system properties even though
`system` service is still in maintenanace from previous test case. Then, it reads the retry counter in `/inventory/retries` endpoint to assert it with the number of retries happened to get the system properties from `inventory` service.

** The `inventory` service should retry the same number of times as stated by the `maxRetries` attribute in the `@Retry` annotation to get the system properties. However, it makes a first call on the annotated method assuming that `system` service is avialable. As a result, the total calls on this method are four.

To force these test cases to execute in a particular order, put them in a testSuite() method and label it with 
a `@Test` annotation so that it automatically executes when your test class run.

include::{common-includes}/mvnverify.adoc[]

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running it.io.openliberty.guides.faulttolerance.FaultToleranceTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.322 sec - in it.io.openliberty.guides.faulttolerance.FaultToleranceTest
Running it.io.openliberty.guides.inventory.EndpointTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.307 sec - in it.io.openliberty.guides.inventory.EndpointTest

Results :

Tests run: 2, Failures: 0, Errors: 0, Skipped: 0
```

To see whether the tests detect a failure, remove the reset retries method of 
the `FaultToleranceTest.java` file. Re-run the Maven build. You will see a test failure occur for the 
testRetryGettingSystemProperties() test case.

// =================================================================================================
// Great work! You're done!
// =================================================================================================

== Great work! You're done!

You just built and tested a MicroProfile application with MicroProfile Fault Tolerance and Open Liberty.

You can continue to try one of the related guides, which demonstrate new technologies that you can 
learn and expand on top what you built in this guide.


include::{common-includes}/finish.adoc[]
