// Copyright (c) 2018 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//   IBM Corporation
:projectid: microprofile-retry-fallback
:page-layout: guide
:page-duration: 20 minutes
:page-releasedate: 2018-02-12
:page-description: Learn how to add retry and fallback behavior to microservice dependencies to manage the impact of failures.
:page-tags: ['REST', 'MicroProfile', 'microservices', 'Fault Tolerance', '@Retry', '@Fallback']
:page-permalink: /guides/{projectid}
:page-related-guides: ['rest-intro', 'cdi-intro', 'microprofile-config', 'circuit-breaker']
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
:source-highlighter: prettify
= Building fault tolerant microservices with the @Retry and @Fallback annotations

Learn how to add retry and fallback behavior to microservice dependencies to manage the impact of failures.

// =================================================================================================
// What you'll learn
// =================================================================================================

== What you'll learn

You will learn how to build fault tolerant microservices in an inventory management application so 
that you can reduce the impact from failure and ensure continued operation of services.

The application that you will be working with is an `inventory` service, which stores the information 
about various JVMs that run on different systems. Whenever a request is made to the `inventory` service
to retrieve the JVM system properties of a particular host, the `inventory` service communicates with 
the `system` service on that host to get these system properties. The system properties are then stored 
and returned.

You will use the `@Retry` and `@Fallback` annotations, from the MicroProfile (MP) Fault Tolerance 
specification, to define a criteria on when to retry and when to provide an alternative solution for 
a failed execution. Fault Tolerance enables the application to function even when one of it's services
is unavailable, making service invocation more resilient.

The implementation of the application and its services are provided for you.
The `system` service can be found in `src/main/java/io/openliberty/guides/system`, and the `inventory`
service can be found in `src/main/java/io/openliberty/guides/inventory`. If you want to learn how to
create a RESTful application, see https://openliberty.io/guides/rest-intro.html[Creating a RESTful web service].

// =================================================================================================
// Why use MicroProfile Fault Tolerance?
// =================================================================================================

=== Why use MicroProfile Fault Tolerance?

It is becoming increasingly important to build fault tolerant microservices and MicroProfile (MP)
Fault Tolerance provides a simple and flexible solution.
Fault tolerance is about leveraging different strategies to guide the execution and result of some logic.
Retry policies, bulkheads, and circuit breakers are popular concepts in this area.
They dictate whether and when executions should take place, and fallbacks offer an alternative result
when an execution does not complete successfully.

MP Fault Tolerance offers the following Fault Tolerance policies:

* Timeout: Define a duration for timeout

* Retry: Define a criteria on when to retry

* Fallback: provide an alternative solution for a failed execution

* CircuitBreaker: offer a way of fail fast by automatically failing execution to prevent the system
overloading and indefinite wait or timeout by the clients

* Bulkhead: isolate failures in part of the system while the rest part of the system can still function

In this guide we will be focusing on `@Retry` and `@Fallback`.


// =================================================================================================
// Getting Started
// =================================================================================================

include::{common-includes}/gitclone.adoc[]

// =================================================================================================
// Try what you'll build
// =================================================================================================

=== Try what you'll build

The `finish` directory in the root of this guide contains the finished fault tolerance implementation
for the application. Feel free to give it a try before you proceed with building your own.

To try out the application, first navigate to the `finish` directory and then execute the following
Maven goals to build the application and run it inside Open Liberty:

```
mvn clean install liberty:start-server

```

Point your browser to the `http://localhost:9080/inventory/systems/localhost` URL. You see a result
in JSON format with the system properties of your local JVM. When you visit this URL, these system 
properties are automatically stored in the inventory.

Now open the `finish/resource/CustomConfigSource.json` and change the property 
`io_openliberty_guides_system_inMaintenance` from `false` to `true` and save the file. There is no need
to restart the server. Now return to your browser and point back to the 
`http://localhost:9080/inventory/systems/localhost` URL. You will now see the cached properties from
systems for this localhost due to the `system` service now being in maintenance. For simplicity, only
the OS name and username are stored in cache for each host. 

Once you are done checking out the application, go to the `CustomConfigSource.json` file again and
change the property `io_openliberty_guides_system_inMaintenance` from `true` to `false` to set this
condition back to its original value.

Stop the Open Liberty server:

```
mvn liberty:stop-server
```

Now, navigate back to the `start` directory to begin.


// =================================================================================================
// Enabling Fault Tolerance in the application
// =================================================================================================

== Enabling Fault Tolerance in the application

The MicroProfile Fault Tolerance API has been added as a dependency to your `pom.xml` file. Look for
the dependancy with the groupID `org.eclipse.microprofile.fault-tolerance`. This feature allows you
to use the MicroProfile Fault Tolerance API to build fault tolerant microservices.
The `mpFaultTolerance-1.0` feature has also been enabled in the `src/main/liberty/config/server.xml`
file.


To make it easy for you to work through this guide, the two microservices provided are setup to run
on the same server. To simulate availability of the services and then to enable fault tolerance, 
dynamic configuration using MicroProfile Configuration is used to allow you to easily take one service
or the other down for maintenance. If you want to learn more about setting up dynamic configuration,
see https://openliberty.io/guides/microprofile-config.html[Configuring microservices].

To enable fault tolerance in the application, create the `SystemClient` class in the
`src/main/java/io/openliberty/guides/inventory/client/SystemClient.java` file:

[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/inventory/client/SystemClient.java[tags=throw_IOException;!copyright;!javadoc]
----
This class is a client for the `system` service.

In this class there is a method called `getPropertiesHelper()`. This method makes a request to the
`system` service, and checks for the response. If a `Status.OK`` response which is corresponding to the
200 status code is found, the method returns the system properties from the `system` service request.
In this guide, a new if statement has been added to the method to check if the response is specifically
a `Status.SERVICE_UNAVAILABLE` that is a 503 status code. When this happens, the server being called
is unable to handle the request due to a temporary overload or scheduled maintenance, which would
likely be alleviated after some delay. To simulate system being unavailable, an IOException is thrown.

This `getPropertiesHelper()` method is called by the public `getProperties()` method which is used 
in `InventoryManager.java`. You will look into this class in more detail in the next section.


// =================================================================================================
// Getting the System Properties
// =================================================================================================

=== Getting the System Properties 

Create the `SystemResource` class in the 
`src/main/java/io/openliberty/guides/system/SystemResource.java` file:

[source, java]
----
include::finish/src/main/java/io/openliberty/guides/system/SystemResource.java[tags=503_response]
----

The service invokes the `getProperties()` method to display the system properties for a specific
host. The host displays only if you set the `io_openliberty_guides_system_inMaintenance` configuration 
to `false` in the `finish/resource/CustomConfigSource.json` file. Otherwise, the service throws an 
exception which makes it unavailable.

// =================================================================================================
// Adding the @Retry and @Fallback annotations
// =================================================================================================

=== Adding the @Retry and @Fallback annotations

Our `inventory` microservice is now able to recognise that the `system` microservice has been taken
down for maintenance through the 503 HTTP response returned. As a result, it has thrown an IOException.
A fallback method now needs to be set out to deal with this failure.
Create the `InventoryManager` class in the 
`src/main/java/io/openliberty/guides/inventory/InventoryManager.java` file:

[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/inventory/InventoryManager.java[tags=add_retry_fallback]
----

The `@Retry` annotation dictates on what conditions we should reattempt to establish a connection
to the `system` service and how many times it should be retried, in this case three times.
The `@Fallback` annotation dictates which method to call when the retries are unsuccessful, in this
case the fallbackForGet method can be used.

The `fallbackForGet()` method that has been added as the designated fallback method for the original
get() method, checks to see if the system's properties exist in the inventory. If the properties do 
not exist, this suggests that the application has not been able to successfully reach the `system`
service to get the system’s properties previously, thus the method simply prints out a json warning 
message in the browser. Otherwise, this method returns the cached property values.

The application has now been successfully set up to be fault tolerant.


// =================================================================================================
// Building and running the application
// =================================================================================================

include::{common-includes}/mvnbuild.adoc[]

Once the server is running, point your browser to the 
`http://localhost:9080/inventory/systems/localhost` URL.
You see a result in JSON format with the system properties of your local JVM. Next, point your 
browser to the `http://localhost:9080/system/properties` URL which retrieves the information for a
specific host. You can test the fault tolerance mechanism of your application by dynamically changing
the `io_openliberty_guides_system_inMaintenance` property value to `true` in the 
`resource/CustomConfigSource.json` file. After saving the file, go back to your browser and click 
refresh to the `http://localhost:9080/inventory/systems/localhost` URL to see the cached version of 
the properties. Point your browser again to the `http://localhost:9080/system/properties` URL and you
will notice that it is no longer available. The cached system properties only have the OS name and 
username key and value pairs. Once you're done, change the `io_openliberty_guides_system_inMaintenance` 
property value back to `false` in the `resource/CustomConfigSource.json` file.

include::{common-includes}/mvnpackage.adoc[]


// =================================================================================================
// Testing the application
// =================================================================================================

== Testing the application

While you can test your application manually, you should rely on automated tests since they will
trigger a failure whenever a code change introduces a defect. Since the application is a RESTful 
web service application, you can use JUnit and the RESTful web service Client API to write tests. 

Create the `FaultToleranceTest` class in the 
`src/test/java/it/io/openliberty/guides/faulttolerance/FaultToleranceTest.java` file:

[source, java]
----
include::finish/src/test/java/it/io/openliberty/guides/faulttolerance/FaultToleranceTest.java[tags=ft_testing;!javadoc]
----

The `@BeforeClass` annotation is placed on a method that executes before any of the test cases. In
this case, the `oneTimeSetup()` method retrieves the port number for the Open Liberty server and 
builds a base URL string that is used throughout the tests.

The `@Before` and `@After` annotations are placed on methods that execute before and after every 
test case. These methods are generally used to perform any setup and teardown tasks. In this case,
the setup method creates a JAX-RS client which makes HTTP requests to the `inventory` service. This
client must also be registered with a JSON-P provider (JsrJsonpProvider) to process JSON resources. 
The teardown method simply destroys this client instance as well as the HTTP responses, resets the
changed configuration file and the retry counter.

Let’s break down the test cases:

* `testFallbackForGet()` sends a request to `inventory` service to get the systems properties for a
hostname, when `system` service is available. Then, it puts the `system` service on maintenance. The
`inventory` service returns the properties from making a connection to `system` service.
After that, it makes a second request to `inventory` service to return the system properties for that
hostname. The fallback method from `inventory` service is called to return the cached properties. 
Lastly, it asserts if the system properties returned from the first request were more than the second
request.

* `testRetryGettingSystemProperties()` also sends a request to `inventory` service to try to get the
system properties. Then, it reads the retry counter in `/inventory/retries` endpoint to assert it 
with the number of retries happened to get the system properties from `inventory` service. The 
`inventory` service should retry the same number of times as stated by the `maxRetries` attribute
in the `@Retry` annotation to get the system properties. However, it makes a first call on the 
annotated method assuming that `system` service is available. As a result, the total calls on this
method are four.

To force these test cases to execute in a particular order, put them in a testSuite() method and label
it with a `@Test` annotation so that it automatically executes when your test class run.

In addition, a few endpoint tests have been included for you to test the basic functionality of the
`inventory` and `system` services.  If a test failure occurs, then you must have introduced a bug into
the code.

// =================================================================================================
// Running the tests
// =================================================================================================

include::{common-includes}/mvnverify.adoc[]

[source, role="no_copy"]
----
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running it.io.openliberty.guides.system.SystemEndpointTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.937 sec - in it.io.openliberty.guides.system.SystemEndpointTest
Running it.io.openliberty.guides.inventory.InventoryEndpointTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.396 sec - in it.io.openliberty.guides.inventory.InventoryEndpointTest
Running it.io.openliberty.guides.faulttolerance.FaultToleranceTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.517 sec - in it.io.openliberty.guides.faulttolerance.FaultToleranceTest

Results :

Tests run: 3, Failures: 0, Errors: 0, Skipped: 0
----

To see whether the tests detect a failure, remove the reset retries method of
the `FaultToleranceTest.java` file. Re-run the Maven build. You will see a test failure occur for the
`testRetryGettingSystemProperties()` test case.

// =================================================================================================
// Great work! You're done!
// =================================================================================================

== Great work! You're done!

You just built and tested a micorservice application with MicroProfile Fault Tolerance and Open Liberty.

Feel free to try one of the related MicroProfile guides. They demonstrate new technologies that you can
learn and expand on top what you built here.

include::{common-includes}/finish.adoc[]
