// Copyright (c) 2018, 2019 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//   IBM Corporation
:projectid: microprofile-fallback
:page-layout: guide-multipane
:page-duration: 20 minutes
:page-releasedate: 2018-03-16
:page-guide-category: microprofile
:page-essential: false
:page-description: Learn how to add fallback behavior to microservice dependencies to manage the impact of failures.
:page-tags: ['MicroProfile']
:page-permalink: /guides/{projectid}
:page-related-guides: ['rest-intro', 'cdi-intro', 'microprofile-config', 'circuit-breaker']
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
:source-highlighter: prettify
:guide-author: Open Liberty
= Building fault-tolerant microservices with the @Fallback annotation

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form, view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website].

You'll explore how to manage the impact of failures using MicroProfile Fault Tolerance by adding fallback behavior to microservice dependencies.

// =================================================================================================
// What you'll learn
// =================================================================================================

== What you'll learn

You will learn how to use MicroProfile (MP) Fault Tolerance to build resilient microservices
that reduce the impact from failure and ensure continued operation of services.

MP Fault Tolerance provides a simple and flexible solution to build fault-tolerant microservices.
Fault tolerance leverages different strategies to guide the execution and result of logic.
As stated in the https://microprofile.io/project/eclipse/microprofile-fault-tolerance[MicroProfile website^],
retry policies, bulkheads, and circuit breakers are popular concepts in this area.
They dictate whether and when executions take place, and fallbacks offer an alternative result
when an execution does not complete successfully.

The application that you will be working with is an `inventory` service, which collects,
stores, and returns the system properties.
It uses the `system` service to retrieve the system properties for a particular host.
You will add fault tolerance to the `inventory` service so that it reacts accordingly when the `system`
service is unavailable.

You will use the `@Fallback` annotations from the MicroProfile Fault Tolerance
specification to define criteria for when to provide an alternative solution for
a failed execution.

You will also see the application metrics for the fault tolerance methods that are automatically enabled
when you have the MicroProfile Metrics feature added to the application server configuration file.


// =================================================================================================
// Getting Started
// =================================================================================================

[role='command']
include::{common-includes}/gitclone.adoc[]

// =================================================================================================
// Try what you'll build
// =================================================================================================

=== Try what you'll build

The `finish` directory in the root of this guide contains the finished implementation
for the application. You can give it a try before you proceed with building your own.

To try out the application, navigate to the `finish` directory and run the following command:

[role='command']
```
mvn install liberty:start-server
```

Point your browser to the http://localhost:9080/inventory/systems/localhost[http://localhost:9080/inventory/systems/localhost^] URL, which accesses the
`inventory` service with a localhost host name. You see the system properties for this host.
When you visit this URL, some of these system
properties, such as the OS name and user name, are automatically stored in the inventory.

[role="code_command hotspot", subs="quotes"]
----
#Update the `CustomConfigSource` configuration file.#
`resources/CustomConfigSource.json`
----

CustomConfigSource.json
[source, JSON, linenums, role='code_column']
----
include::finish/resources/CustomConfigSource.json[]
----

[role="edit_command_text"]
Change the [hotspot=2]`io_openliberty_guides_system_inMaintenance` property from `false` to `true` and save the file.

You do not need
to restart the server. Next, return to your browser and point back to the
http://localhost:9080/inventory/systems/localhost[http://localhost:9080/inventory/systems/localhost^] URL.
The fallback mechanism is triggered because the `system` service is now in maintenance.
You see the cached properties for this localhost.

When you are done checking out the application, go to the [hotspot]`CustomConfigSource.json` file again.

[role="code_command hotspot", subs="quotes"]
----
#Update the `CustomConfigSource` configuration file.#
`resources/CustomConfigSource.json`
----

[role="edit_command_text"]
Change the [hotspot=2]`io_openliberty_guides_system_inMaintenance` property from `true` to `false` to set this
condition back to its original value.

Stop the Open Liberty server:

[role='command']
```
mvn liberty:stop-server
```

// =================================================================================================
// Enabling fault tolerance
// =================================================================================================

== Enabling fault tolerance

Navigate to the `start` directory to begin.

The MicroProfile Fault Tolerance API was added as a dependency to your [hotspot file=4]`pom.xml` file. Look for
the dependency with the [hotspot=73-78 file=4]`mpFaultTolerance` artifact ID. Adding this dependency allows you to use the
fault tolerance policies in your microservices.

You can also find the [hotspot=9 file=3]`mpFaultTolerance` feature in your [hotspot file=3]`src/main/liberty/config/server.xml` server configuration,
which turns on MicroProfile Fault Tolerance capabilities in Open Liberty.

To easily work through this guide, the two provided microservices are set up to run
on the same server. To simulate the availability of the services and then to enable fault tolerance,
dynamic configuration with MicroProfile Configuration is used so that you can easily take one service
or the other down for maintenance. If you want to learn more about setting up dynamic configuration,
see https://openliberty.io/guides/microprofile-config.html[Configuring microservices^].

The following two steps set up the dynamic configuration on the `system` service and its client.
You can move on to the next section, which adds the fallback mechanism on the `inventory` service.

First, the [hotspot file=0]`src/main/java/io/openliberty/guides/system/SystemResource.java` file has
the [hotspot=21-23 file=0]`isInMaintenance()` condition, which determines that the system properties are returned only if you
set the [hotspot=2 file=1]`io_openliberty_guides_system_inMaintenance` configuration property
to `false` in the [hotspot file=1]`CustomConfigSource` file.
Otherwise, the service returns a [hotspot=24 file=0]`Status.SERVICE_UNAVAILABLE` message, which makes it unavailable.

Next, the [hotspot file=2]`src/main/java/io/openliberty/guides/inventory/client/SystemClient.java` file
makes a request to the `system` service through the MicroProfile Rest Client API.
If you want to learn more about MicroProfile Rest Client,
you can follow the https://openliberty.io/guides/microprofile-rest-client.html[Consuming RESTful services with template interfaces^] guide.
The `system` service as described in the [hotspot file=0]`SystemResource.java` file
may return a [hotspot=24 file=0]`Status.SERVICE_UNAVAILABLE` message, which is a 503 status code.
This code indicates that the server being called
is unable to handle the request because of a temporary overload or scheduled maintenance, which would
likely be alleviated after some delay. To simulate that the system is unavailable, an [hotspot=22 file=2]`IOException` is thrown.

The `InventoryManager` class calls the [hotspot=21-23 file=2]`getProperties()` method
in the [hotspot file=2]`SystemClient.java` class.
You will look into the `InventoryManager` class in more detail in the next section.

SystemResource.java
[source, java, linenums, role='code_column']
----
include::finish/src/main/java/io/openliberty/guides/system/SystemResource.java[tags=503_response]
----

CustomConfigSource.json
[source, JSON, linenums, role='code_column']
----
include::finish/resources/CustomConfigSource.json[]
----

SystemClient.java
[source, java, linenums, role='code_column']
----
include::finish/src/main/java/io/openliberty/guides/inventory/client/SystemClient.java[tags=client]
----

server.xml
[source, xml, linenums, role='code_column']
----
include::finish/src/main/liberty/config/server.xml[]
----

pom.xml
[source, xml, linenums, role='code_column']
----
include::finish/pom.xml[tags=**]
----

// =================================================================================================
// Adding the @Fallback annotation
// =================================================================================================

=== Adding the @Fallback annotation

The `inventory` service is now able to recognize that the `system` service
was taken down for maintenance.
An IOException is thrown to simulate the `system` service is unavailable.
Now, set a fallback method to deal with this failure.


[role="code_command hotspot", subs="quotes"]
----
#Create the `InventoryManager` class.#
`src/main/java/io/openliberty/guides/inventory/InventoryManager.java`
----

InventoryManager.java
[source, java, linenums, role='code_column']
----
include::finish/src/main/java/io/openliberty/guides/inventory/InventoryManager.java[tags=add_fallback]
----

The [hotspot=18]`@Fallback` annotation dictates a method to call when the original method encounters a failed execution. In this
example, use the [hotspot=23-31]`fallbackForGet()` method.

The [hotspot=23-31]`fallbackForGet()` method, which is the designated fallback method for the original
[hotspot=19-21]`get()` method, checks to see if the system's properties exist in the inventory.
If the system properties entry is not found in the inventory, the method prints out a warning
message in the browser. Otherwise, this method returns the cached property values from the inventory.

You successfully set up your microservice to have fault tolerance capability.


== Viewing metrics for the fault tolerance methods

server.xml
[source, xml, linenums, role='code_column']
----
include::finish/src/main/liberty/config/server.xml[]
----

MicroProfile Fault Tolerance integrates with MicroProfile Metrics to provide metrics for the annotated fault tolerance methods.
When both the [hotspot=mpFaultTolerance]`mpFaultTolerance` and the [hotspot=mpMetrics]`mpMetrics` features are included in the [hotspot]`server.xml` configuration file,
the `@Fallback` fault tolerance annotation supplies metrics that count the total number of annotated method invocations and failed invocations, 
as well, the total number of the fallback method calls.

You can learn more about MicroProfile Metrics in the https://openliberty.io/guides/microprofile-metrics.html[Providing metrics from a microservice^] guide.

// =================================================================================================
// Building and running the application
// =================================================================================================

[role='command']
include::{common-includes}/mvnbuild.adoc[]

When the server is running, point your browser to the
http://localhost:9080/inventory/systems/localhost[http://localhost:9080/inventory/systems/localhost^] URL.
You receive the system properties of your local JVM from the `inventory` service. Next, point your
browser to the `system` service URL, which is located at http://localhost:9080/system/properties[http://localhost:9080/system/properties^],
to retrieve the system properties for the specific localhost.
Notice that the results from the two URLs are identical because the `inventory` service gets its results from
calling the `system` service.

[role="code_command", subs="quotes"]
----
#Update the configuration file.#
`resources/CustomConfigSource.json`
----

CustomConfigSource.json
[source, json, linenums, role='code_column']
----
include::finish/resources/CustomConfigSource.json[]
----

InventoryManager.java
[source, java, linenums, role='code_column']
----
include::finish/src/main/java/io/openliberty/guides/inventory/InventoryManager.java[tags=add_fallback]
----

To see the application metrics, point your browser to https://localhost:9443/metrics/application[https://localhost:9443/metrics/application^].
See the following sample outputs for the `@Fallback` annotated method and the fallback method before a fallback occurs:

[role="no_copy"]
----
# TYPE application:ft_io_openliberty_guides_inventory_inventory_manager_get_invocations_total counter
application:ft_io_openliberty_guides_inventory_inventory_manager_get_invocations_total 1
# TYPE application:ft_io_openliberty_guides_inventory_inventory_manager_get_invocations_failed_total counter
application:ft_io_openliberty_guides_inventory_inventory_manager_get_invocations_failed_total 0
# TYPE application:ft_io_openliberty_guides_inventory_inventory_manager_get_fallback_calls_total counter
application:ft_io_openliberty_guides_inventory_inventory_manager_get_fallback_calls_total 0
----

You can test the fault tolerance mechanism of your microservices by dynamically changing
the [hotspot=2 file=0]`io_openliberty_guides_system_inMaintenance` property value to `true` in the
[hotspot file=0]`resources/CustomConfigSource.json` file, which turns the `system` service in maintenance.
After saving the file, go back to your browser and
refresh to the http://localhost:9080/inventory/systems/localhost[http://localhost:9080/inventory/systems/localhost^] URL to view the cached version of
the properties. The [hotspot=23-31 file=1]`fallbackForGet()` method, which is the designated fallback method, is called
when the `system` service is not available.
The cached system properties contain only the OS name and user name key and value pairs.

To see that the `system` service is down, point your browser to the http://localhost:9080/system/properties[http://localhost:9080/system/properties^] URL again.
You see that the service displays a 503 HTTP response code.

Point your browser to https://localhost:9443/metrics/application[https://localhost:9443/metrics/application^] again.
See the following sample outputs for the `@Fallback` annotated method and the fallback method after a fallback occurs:

[role="no_copy"]
----
# TYPE application:ft_io_openliberty_guides_inventory_inventory_manager_get_invocations_total counter
application:ft_io_openliberty_guides_inventory_inventory_manager_get_invocations_total 2
# TYPE application:ft_io_openliberty_guides_inventory_inventory_manager_get_invocations_failed_total counter
application:ft_io_openliberty_guides_inventory_inventory_manager_get_invocations_failed_total 0
# TYPE application:ft_io_openliberty_guides_inventory_inventory_manager_get_fallback_calls_total counter
application:ft_io_openliberty_guides_inventory_inventory_manager_get_fallback_calls_total 1
----

When you're done, change the [hotspot=2]`io_openliberty_guides_system_inMaintenance`
property value back to `false` in the [hotspot file=0]`resources/CustomConfigSource.json` file.

include::{common-includes}/mvncompile.adoc[]


// =================================================================================================
// Testing the application
// =================================================================================================

== Testing the application

You can test your application manually, but automated tests ensure code quality because they trigger a failure
whenever a code change introduces a defect. JUnit and the JAX-RS Client API provide a simple environment for you to write tests.

[role="code_command hotspot", subs="quotes"]
----
#Create the `FaultToleranceTest` class.#
`src/test/java/it/io/openliberty/guides/faulttolerance/FaultToleranceTest.java`
----

The [hotspot=21]`@Before` and [hotspot=27]`@After` annotations indicate that this method executes before or after the other test case.
These methods are generally used to perform any setup and teardown tasks. In this case,
the setup method creates a JAX-RS client, which makes HTTP requests to the `inventory` service. This
client must also be registered with a JSON-P provider to process JSON resources.
The teardown method simply destroys this client instance as well as the HTTP responses.

The [hotspot=34-53]`testFallbackForGet()` test case sends a request to the `inventory` service to get the systems properties for a
host name before and after the `system` service becomes unavailable. Then, it asserts outputs from the two requests
to ensure that they are different from each other.

The [hotspot=33]`@Test` annotation indicates that the method automatically executes when your test class runs.

In addition, a few endpoint tests have been included for you to test the basic functionality of the
`inventory` and `system` services. If a test failure occurs, then you might have introduced a bug into
the code.

FaultToleranceTest.java
[source, java, linenums, role='code_column']
----
include::finish/src/test/java/it/io/openliberty/guides/faulttolerance/FaultToleranceTest.java[tags=ft_testing;!javadoc]
----
// =================================================================================================
// Running the tests
// =================================================================================================

[role='command']
include::{common-includes}/mvnverify.adoc[]

[source, role="no_copy"]
----
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running it.io.openliberty.guides.system.SystemEndpointTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.937 sec - in it.io.openliberty.guides.system.SystemEndpointTest
Running it.io.openliberty.guides.inventory.InventoryEndpointTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.396 sec - in it.io.openliberty.guides.inventory.InventoryEndpointTest
Running it.io.openliberty.guides.faulttolerance.FaultToleranceTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.517 sec - in it.io.openliberty.guides.faulttolerance.FaultToleranceTest

Results :

Tests run: 3, Failures: 0, Errors: 0, Skipped: 0
----

To see if the tests detect a failure, comment out the [hotspot=40-41 hotspot=51-52]`changeSystemProperty()` methods
in the [hotspot]`FaultToleranceTest.java` file. Rerun the Maven build.
You see a test failure occur for the [hotspot=34-53]`testFallbackForGet()` test case.


// =================================================================================================
// Great work! You're done!
// =================================================================================================

== Great work! You're done!

You just learned how to build a fallback mechanism for a microservice with MicroProfile Fault Tolerance in Open Liberty and wrote a test to validate it.

You can try one of the related MicroProfile guides. They demonstrate technologies that you can
learn and expand on what you built here.


include::{common-includes}/attribution.adoc[subs="attributes"]
