// Copyright (c) 2018 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//   IBM Corporation
:projectid: microprofile-retry-fallback
:page-layout: guide
:page-duration: 20 minutes
:page-releasedate: 2018-02-12
:page-description: Learn how to add retry and fallback behavior to microservice dependencies to manage the impact of failures.
:page-tags: ['REST', 'MicroProfile', 'microservices', 'Fault Tolerance', '@Retry', '@Fallback']
:page-permalink: /guides/{projectid}
:page-related-guides: ['rest-intro', 'cdi-intro', 'microprofile-config', 'circuit-breaker']
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
:source-highlighter: prettify
= Building fault-tolerant microservices with the @Retry and @Fallback annotations

You'll explore how to manage the impact of failures using MicroProfile Fault Tolerance by adding retry and fallback behaviors to microservice dependencies.

// =================================================================================================
// What you'll learn
// =================================================================================================

== What you'll learn

You will learn how to build fault-tolerant microservices in an inventory management application so
that you can reduce the impact from failure and ensure continued operation of services.

The application that you will be working with is an `inventory` service, which stores the information
about various JVMs that run on different systems. When you make a request to the `inventory` service
to retrieve the JVM system properties of a particular host, the `inventory` service communicates with
the `system` service on that host to get these system properties.
The `inventory` service then stores and returns the system properties.

You will use the `@Retry` and `@Fallback` annotations from the MicroProfile (MP) Fault Tolerance
specification to define criteria for when to retry and when to provide an alternative solution for
a failed execution. Fault Tolerance enables the application to function even when one of its services
is unavailable, making service invocation more resilient.

The implementation of the application and its services are provided for you.
You can find the `system` service in the `src/main/java/io/openliberty/guides/system` directory, and you can find the `inventory`
service in the `src/main/java/io/openliberty/guides/inventory` directory.
These two services are RESTful web services, if you want to learn how to
create one, see https://openliberty.io/guides/rest-intro.html[Creating a RESTful web service].

// =================================================================================================
// Why use MicroProfile Fault Tolerance?
// =================================================================================================

=== Why use MicroProfile Fault Tolerance?

MP Fault Tolerance provides a simple and flexible solution to build fault-tolerant microservices.
Fault tolerance leverages different strategies to guide the execution and result of logic.
Retry policies, bulkheads, and circuit breakers are popular concepts in this area.
They dictate whether and when executions take place, and fallbacks offer an alternative result
when an execution does not complete successfully.

MP Fault Tolerance offers the following fault tolerance policies:

* Timeout: Defines a duration for timeout

* Retry: Defines a criteria for when to retry

* Fallback: Provides an alternative solution for a failed execution

* CircuitBreaker: Offers a way to fail fast by automatically failing execution and also prevents the system from
overloading and creating an indefinite wait or timeout by the clients

* Bulkhead: Isolates failures in part of the system while the rest of the system can still function

In this guide, you will focus on the `@Retry` and `@Fallback` policies.


// =================================================================================================
// Getting Started
// =================================================================================================

include::{common-includes}/gitclone.adoc[]

// =================================================================================================
// Try what you'll build
// =================================================================================================

=== Try what you'll build

The `finish` directory in the root of this guide contains the finished fault tolerance implementation
for the application. You can give it a try before you proceed with building your own.

To try out the application, first navigate to the `finish` directory. Then, execute the following
Maven goals to build the application and run it inside Open Liberty:

```
mvn clean install liberty:start-server

```

Point your browser to the `http://localhost:9080/inventory/systems/localhost` URL. You see a result
in JSON format with the system properties of your local JVM. When you visit this URL, these system
properties are automatically stored in the inventory.

Now, open the `finish/resource/CustomConfigSource.json` file and change the
`io_openliberty_guides_system_inMaintenance` property from `false` to `true` and save the file. You do not need
to restart the server. Next, return to your browser and point back to the
`http://localhost:9080/inventory/systems/localhost` URL. Because the system service is now in maintenance, you see the cached properties from the systems for this localhost. For simplicity, only the OS name and user name are stored in the cache for each host.

When you are done checking out the application, go to the `CustomConfigSource.json` file again and
change the `io_openliberty_guides_system_inMaintenance` property from `true` to `false` to set this
condition back to its original value.

Stop the Open Liberty server:

```
mvn liberty:stop-server
```

Now, navigate back to the `start` directory to begin.


// =================================================================================================
// Enabling fault tolerance in the application
// =================================================================================================

== Enabling fault tolerance in the application

The MicroProfile Fault Tolerance API is added as a dependency to your `pom.xml` file. Look for
the dependancy with the `org.eclipse.microprofile.fault-tolerance` group ID. Use this feature
to build fault-tolerant microservices with the MicroProfile Fault Tolerance API.
The `mpFaultTolerance-1.0` feature is also enabled in the `src/main/liberty/config/server.xml`
file.


To easily work through this guide, the two provided microservices are set up to run
on the same server. To simulate the availability of the services and then to enable fault tolerance,
dynamic configuration with MicroProfile Configuration is used so that you can easily take one service
or the other down for maintenance. If you want to learn more about setting up dynamic configuration,
see https://openliberty.io/guides/microprofile-config.html[Configuring microservices].

First, create the `SystemResource` class in the
`src/main/java/io/openliberty/guides/system/SystemResource.java` file:

[source, java]
----
include::finish/src/main/java/io/openliberty/guides/system/SystemResource.java[tags=503_response]
----

The service displays the system properties for a specific host.
The `inMaintenance()` condition determines that the system properties are returned only if you
set the `io_openliberty_guides_system_inMaintenance` configuration property
to `false` in the `start/resource/CustomConfigSource.json` file.
Otherwise, the service returns a `Status.SERVICE_UNAVAILABLE` message, which makes it unavailable.

Next, create the `SystemClient` class in the
`src/main/java/io/openliberty/guides/inventory/client/SystemClient.java` file:

[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/inventory/client/SystemClient.java[tags=throw_IOException;!copyright;!javadoc]
----
This class is a client for the `system` service.

This class includes the `getPropertiesHelper()` method. This method makes a request to the
`system` service and checks for the response. If the request response is a `Status.OK` message
that corresponds to the 200 status code, the method returns the system properties from the `system` service request.
In this guide, a new `if` statement is added to the method to check if the response is specifically
a `Status.SERVICE_UNAVAILABLE` message, which is a 503 status code. This code indicates that the server being called
is unable to handle the request because of a temporary overload or scheduled maintenance, which would
likely be alleviated after some delay. To simulate that the system is unavailable, an IOException is thrown.

The public `getProperties()` method in this class calls the `getPropertiesHelper()` method.
The `InventoryManager` class calls this public method.
You will look into `InventoryManager` class in more detail in the next section.


// =================================================================================================
// Adding the @Retry and @Fallback annotations
// =================================================================================================

=== Adding the @Retry and @Fallback annotations

The `inventory` microservice is now able to recognize that the `system` microservice
was taken down for maintenance because of the 503 HTTP response. This method throws an IOException to simulate the system being unavailable.
Now, set a fallback method to deal with this failure.

Create the `InventoryManager` class in the
`src/main/java/io/openliberty/guides/inventory/InventoryManager.java` file:

[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/inventory/InventoryManager.java[tags=add_retry_fallback]
----

The `@Retry` annotation dictates the conditions that determine if the `inventory` service should reattempt to establish a connection
to the `system` service and how many times it should retry. In this example, the `inventory` service retries three times.
The `@Fallback` annotation dictates which method to call when the retries are unsuccessful. In this
example, use the `fallbackForGet` method.

The `fallbackForGet()` method, which is the designated fallback method for the original
`get()` method, checks to see if the system's properties exist in the inventory. If the properties
variable is null, the system properties entry is not found in the inventory.
Thus, the method prints out a JSON warning
message in the browser. Otherwise, this method returns the cached property values.

You have now successfully set up the application to be fault tolerant.


// =================================================================================================
// Building and running the application
// =================================================================================================

include::{common-includes}/mvnbuild.adoc[]

When the server is running, point your browser to the
`http://localhost:9080/inventory/systems/localhost` URL.
You receive a result in JSON format with the system properties of your local JVM. Next, point your
browser to the `http://localhost:9080/system/properties` URL, which retrieves the information for a
specific host. Notice that the results from the two URLs are identical.

You can test the fault tolerance mechanism of your application by dynamically changing
the `io_openliberty_guides_system_inMaintenance` property value to `true` in the
`start/resource/CustomConfigSource.json` file. After saving the file, go back to your browser and
refresh to the `http://localhost:9080/inventory/systems/localhost` URL to view the cached version of
the properties. Point your browser to the `http://localhost:9080/system/properties` URL again, and
notice that it is no longer available. The cached system properties contain only the OS name and
user name key and value pairs. When you're done, change the `io_openliberty_guides_system_inMaintenance`
property value back to `false` in the `resource/CustomConfigSource.json` file.

include::{common-includes}/mvnpackage.adoc[]

// =================================================================================================
// Testing the application
// =================================================================================================

== Testing the application

Although you can test your application manually, automated tests have the advantage of
triggering a failure whenever a code change introduces a defect. Because the application is a RESTful
web service application, you can use JUnit and the REST Client API to write tests.

Create the `FaultToleranceTest` class in the
`src/test/java/it/io/openliberty/guides/faulttolerance/FaultToleranceTest.java` file:

[source, java]
----
include::finish/src/test/java/it/io/openliberty/guides/faulttolerance/FaultToleranceTest.java[tags=ft_testing;!javadoc]
----

The `@BeforeClass` annotation indicates that this method executes before any of the other test cases. In
this case, the `oneTimeSetup()` method retrieves the port number for the Open Liberty server and
builds a base URL string that is used throughout the tests.

The `@Before` and `@After` annotations indicate that this method executes before or after the other test case.
These methods are generally used to perform any setup and teardown tasks. In this case,
the setup method creates a JAX-RS client, which makes HTTP requests to the `inventory` service. This
client must also be registered with a JSON-P provider to process JSON resources.
The teardown method simply destroys this client instance as well as the HTTP responses and resets the
changed configuration file and the retry counter.

Let’s define the test cases:

* The `testFallbackForGet()` test case sends a request to the `inventory` service to get the systems properties for a
host name when the `system` service is available. Then, it puts the `system` service on maintenance.
Afterward, it makes a second request to the `inventory` service to return the system properties for that
host name. This time the `inventory` service calls the fallback method to return the cached properties.
The test case then asserts whether the system properties that returned from the first request were more than the second.

* The `testRetryGettingSystemProperties()` test case prepares the test by setting the `system` service on maintenance.
Then, it sends a request to the `inventory` service to get the system properties.
Next, the test case reads the number of retries from the retry counter by calling the `http://localhost:9080/inventory/retries` URL.
An assertion checks the number of retries to get the system properties from the `inventory` service with the expected hits.
The `inventory` service retries the same number of times as stated by the `maxRetries` attribute in the `@Retry` annotation.
However, the service always makes the first call on the annotated method. As a result, this method has four total calls.

To force these test cases to execute in a particular order, put them in a `testSuite()` method and label
it with a `@Test` annotation so that the method automatically executes when your test class runs.

In addition, a few endpoint tests have been included for you to test the basic functionality of the
`inventory` and `system` services. If a test failure occurs, then you might have introduced a bug into
the code.

// =================================================================================================
// Running the tests
// =================================================================================================

include::{common-includes}/mvnverify.adoc[]

[source, role="no_copy"]
----
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running it.io.openliberty.guides.system.SystemEndpointTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.937 sec - in it.io.openliberty.guides.system.SystemEndpointTest
Running it.io.openliberty.guides.inventory.InventoryEndpointTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.396 sec - in it.io.openliberty.guides.inventory.InventoryEndpointTest
Running it.io.openliberty.guides.faulttolerance.FaultToleranceTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.517 sec - in it.io.openliberty.guides.faulttolerance.FaultToleranceTest

Results :

Tests run: 3, Failures: 0, Errors: 0, Skipped: 0
----

To see if the tests detect a failure, remove the reset retries method on
the `FaultToleranceTest.java` file. Rerun the Maven build. You see a test failure occur for the
`testRetryGettingSystemProperties()` test case.

// =================================================================================================
// Great work! You're done!
// =================================================================================================

== Great work! You're done!

You have just completed building and testing a microservice application with MicroProfile Fault Tolerance and Open Liberty.

You can try one of the related MicroProfile guides. They demonstrate technologies that you can
learn and expand on what you built here.

include::{common-includes}/finish.adoc[]
