// Copyright (c) 2017 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//   IBM Corporation
:projectid: microprofile-fault_tolerance
:page-layout: guide
:page-duration: 30 minutes
:page-releasedate: 2017-12-11
:page-description: Learn how to use the MicroProfile Fault Tolerance specification to enable applications to function even when one of the microservices is unavailable.
:page-tags: ['REST', 'MicroProfile', 'Fault Tolerance', '@Retry', '@Fallback']
:page-permalink: /guides/{projectid}
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
:source-highlighter: prettify
= Handling failures with Fault Tolerance

Learn how to use the MicroProfile Fault Tolerance specification to enable applications to function 
even when one of the microservices is unavailable.

// =================================================================================================
// What you'll learn
// =================================================================================================

== What you'll learn
You will learn how to build fault tolerant microservices so that you can reduce the impact from failure and 
ensure continued operation of services.
You will use the @Retry and @Fallback methods to define a criteria on when to retry and to provide an 
alternative solution for a failed execution.
Fault Tolerance enables the applications to function even when on of the services is unavailable, 
making service invocation more resilient.

This guide will be building on top of the "Configuring Microservices using MicroProfile Config" 
guide so if you wish to learn more about configuration please visit this guide at: 

After starting the application, you will be able to access two microservices to test availability:

* `http://localhost:9080/system/properties` retrieves the information for a specific host

* `http://localhost:9080/inventory/hosts` retrieves the information for a list of all previously 
registered hosts

To learn more about these two microservices and how you can write the MicroProfile application, see
https://openliberty.io/guides/microprofile-intro.html[Creating a MicroProfile application].


// =================================================================================================
// Getting Started
// =================================================================================================

include::{common-includes}/gitclone.adoc[]


// =================================================================================================
// Background Concepts
// =================================================================================================
== Background Concepts
It is becoming increasingly important to build fault tolerant microservices and MicroProfile (MP) 
Fault Tolerance provides a simple and flexible solution.
Fault tolerance is about leveraging different strategies to guide the execution and result of some logic.
Retry policies, bulkheads, and circuit breakers are popular concepts in this area. 
They dictate whether and when executions should take place, and fallbacks offer an alternative result 
when an execution does not complete successfully.

MP Fault Tolerance offers the following Fault Tolerance policies:

* Timeout: Define a duration for timeout

* Retry: Define a criteria on when to retry

* Fallback: provide an alternative solution for a failed execution

* CircuitBreaker: offer a way of fail fast by automatically failing execution to prevent the system 
overloading and indefinite wait or timeout by the clients

* Bulkhead: isolate failures in part of the system while the rest part of the system can still function

In this guide we will be focusing on @Retry and @Fallback.
[source, java, indent=0, role="no_copy"]

// =================================================================================================
// Enabling Fault Tolerance into the application
// =================================================================================================
== Enabling Fault Tolerance into the application

Begin by enabling the MicroProfile Fault Tolerance feature in your `pom.xml` file. This feature allows 
you to use the MicroProfile Fault Tolerance API to build fault tolerant microservices.
Navigate to the `start/pom.xml` file and add the required dependency:
[source, xml, indent=0]
----
include::finish/pom.xml[tags=fault_tolerance]
----
The mp-config feature also needs to be added to the `start/src/main/liberty/config/server.xml` file:
[source, xml, indent=0]
----
include::finish/src/main/liberty/config/server.xml[tags=fault_tolerance]
----
Now that the MicroProfile Fault Tolerance feature has been enabled, 
navigate to the PorpertiesResource.java file to begin setting up the application's fallback mechanism.

For ease of use, the two microservice being run in this application are being "serverd up" 
by the same server.
This means that one cannot be taken down without the other.
To overcome this challenge, we will imitate the HTTP responses and Exceptions that would normally be 
executed when a server cannot be reached due to the server being taken down Maintanence.

In this PropertiesResource file input the following:

[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/system/PropertiesResource.java[tags=503_response]
----
The new if, else statement here means that if the config property `io_openliberty_guides_system_inMaintenance` 
is assigned the value of false the PropertiesResource class returns a json object of the system properties. 
However if this config prooerty is assigned a value of true, then the PropertiesResource class returns a 
503 HTTP response and prints a message to the terminal to let the developer know that the service is down.

This 503 HTTP response needs to be recognised and acted upon by the other microservice of our application 
(Inventory). To do this, navigate to the InventoryUtil.java file and modify the existing class with the following:

[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/inventory/InventoryUtil.java[tags=throw_IOException]
----

In this class, a new `serverUnavailableHelper()` method has been added. This method checks the HTTP response 
returned by the PropertiesResource.java class. Unlike the responseOKHelper method, which is checking if 
the response is ok (a 200 response), this method checks for the server unavailable response (a 503 response).
If the response is a 503 (i.e. the service is in maintenance), then false is returned. 

The returned value of the `serverUnavailableHelper()` method called by the `getPropertiesHelper()` method. 
If the server is down and serverUnavaliable helper therefore returns false, then an IOException is thrown 
by `getPropertiesHelper()`.

// =================================================================================================
// Adding the @Retry and @Fallback annotations
// =================================================================================================
== Adding the @Retry and @Fallback annotations

Now that our inventory microservice is able to recognise that the system microservice has been taken 
down for maintenance through the 503 HTTP response retruned as a result and has thrown an IOException 
as a result of this microservice being in maintanence, a fallback method needs to be set out.
Navigate to the InventoryManager.java file in `finish/src/main/io/openliberty/guides/inventory` and 
add the following code to override the existing class:

[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/inventory/InventoryManager.java[tags=add_retry_fallback]
----

The `@Retry` annotation specified here dictates on what conditions to retry establishing the connection 
to the system service (i.e. on an IOException) and how many times it should be retried (i.e. 3 times).
The `@Fallback` annotation specified dictates which method to call when the reties are unsuccessful 
(in this case use the fallbackForGet method).

The `fallbackForGet()` method that has been added as the designated fallback method for the original `get()` 
method, checks to see if the properties variable is null. If the properties variable is null, this suggests 
that the application has not been able to successfully reach the system service to get the system's 
properties previously, thus the method simply prints out a json warning message in the browser. However, if 
the properties variable is not null, this method retruns a json of the cached property values to the browser.


Next navigate to the InventoryResource.java file and modify this existing file with the following code:

[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/inventory/InventoryResource.java[tags=fault_tolerance]
----

The if statement in this class now returns an error message when the inventory service is down for maintanence 
and calls the `get()` method in the InventoryManager.java class when the inventory service is up and running 
as normal.
All references to the email configuration property have been removed from this file.

The application has now been sucessfully set up to be fault tolerant.


// =================================================================================================
// Building the application
// =================================================================================================

include::{common-includes}/mvnbuild.adoc[]


// =================================================================================================
// Starting the application
// =================================================================================================

== Starting the application

To see the new application in action, run the Maven `liberty:start-server` command from the `start` 
directory:

[source]
----
$ mvn liberty:start-server
----

Once the server is running, you can find the service that retrieves configuration information that is 
specific to this guide at the following location:

* `http://localhost:9080/inventory/config/all`

The following two microservices should be available to access initially:

* `http://localhost:9080/inventory/hosts`

* `http://localhost:9080/system/properties`

At first, the `config_ordinal` value of the custom configuration source is set to `500`.
A value of `500` does not override configuration values of the default `microprofile-config.properties` 
source, which has a `config_ordinal` value of `600`.

However, you can manually change the `config_ordinal` value to a larger number in the 
`CustomConfigSource.json` file.

Restart the application. Play with this application by changing configuration values for each property 
in the `CustomConfigSource.json` file.

For example, change `io_openliberty_guides_inventory_inMaintenance` from `false` to `true`, then try to 
access `http://localhost:9080/inventory/hosts` again,
you can see a message that says `Service is temporarily down for maintenance`.

Your changes are added dynamically, and you do not need to restart the server.
Refresh the pages to see the dynamic changes.


// =================================================================================================
// Testing the application
// =================================================================================================

== Testing the application

Add the following test cases to the corresponding locations in the 
`start/src/test/java/it/io/openliberty/guides/microprofile/ConfigurationTest.java` file:

[source, java, indent=0]
----
include::finish/src/test/java/it/io/openliberty/guides/config/ConfigurationTest.java[tags=testInitialServiceStatus()]
----

The `testInitialServiceStatus()` test case reads the value of the 
`io_openliberty_guides_inventory_inMaintenance` configuration property in the file 
`META-INF/microprofile-config.properties` and checks the HTTP response of the inventory service. 
If the configuration value is `false`, the service returns a valid response. Otherwise,
the service returns a message that says, `Service is temporarily down for maintenance`.


[source, java, indent=0]
----
include::finish/src/test/java/it/io/openliberty/guides/config/ConfigurationTest.java[tags=testOverrideConfigProperty()]
----

Because the `META-INF/microprofile-config.properties` default source has the highest ordinal value 
of `600` in the beginning,
the `testOverrideConfigProperty()` test case first checks that the `http://localhost:9080/inventory/config/all`
 microservice contains
the `io_openliberty_guides_testConfigOverwrite` test property with the `DefaultSource` value, which is set by 
this default file.
Then, the test changes the ordinal value of the custom configuration source from `500` to `700` so that the 
custom configuration source becomes the highest priority. In the end, the `CustomSource` value overrides the 
test property.


[source, java, indent=0]
----
include::finish/src/test/java/it/io/openliberty/guides/config/ConfigurationTest.java[tags=testPutServiceInMaintenance()]
----

Because the `io_openliberty_guides_inventory_inMaintenance` configuration property is set to `false` by 
default, the `testPutServiceInMaintenance()` test case first checks that the inventory service is not in 
maintenance in the beginning. Next,
this test increases the priority of the custom configuration source and switches the value of the 
`io_openliberty_guides_inventory_inMaintenance` configuration property
to `true`. In the end, the inventory service returns a message that says, `Service is temporarily down 
for maintenance`.


Add the test suite method:
[source, java, indent=0]
----
include::finish/src/test/java/it/io/openliberty/guides/config/ConfigurationTest.java[tags=testSuite]
----

=== Running the tests

Reset the `microprofile-config.properties` file and the `CustomConfigSource.json` file to the following 
original values before you run tests.
Some of the test cases assume the default configuration.
[source, java, indent=0]
----
include::finish/src/main/resources/META-INF/microprofile-config.properties[tags=all-props]
----

```
{   "config_ordinal": 500,
    "io_openliberty_guides_inventory_inMaintenance": false,
    "io_openliberty_guides_system_inMaintenance": false,
    "io_openliberty_guides_email": "admin@guides.openliberty.io",
    "io_openliberty_guides_testConfigOverwrite": "CustomSource"
}
```

To rebuild and run the tests, navigate to the `start` directory and run the `mvn clean install` command
from the command line:

[source, role="no_copy"]
----
# Stop the server if it is still running from previous steps:
$ mvn liberty:stop-server

# Next, execute the command:
$ mvn clean install
----

The program might take some time to execute the tests. If the tests pass, you receive the following output:

[source, role="no_copy"]
----
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running it.io.openliberty.guides.microprofile.ConfigurationTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.324 sec - in 
it.io.openliberty.guides.microprofile.ConfigurationTest

Results :

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0

----

== Great work! You're done!

You just built and tested a MicroProfile application with MicroProfile Config and Open Liberty.

include::{common-includes}/finish.adoc[]
