// Copyright (c) 2018 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//   IBM Corporation
:projectid: microprofile-retry-fallback
:page-layout: guide
:page-duration: 20 minutes
:page-releasedate: 2018-02-12
:page-description: Learn how to add retry and fallback behavior to microservice dependencies to manage the impact of failures.
:page-tags: ['REST', 'MicroProfile', 'microservices', 'Fault Tolerance', '@Retry', '@Fallback']
:page-permalink: /guides/{projectid}
:page-related-guides: ['rest-intro', 'cdi-intro', 'microprofile-config', 'circuit-breaker']
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
:source-highlighter: prettify
= Building fault-tolerant microservices with the @Retry annotation

You’ll explore how to add retry and fallback behavior to microservice dependencies to manage the impact of failures.

// =================================================================================================
// What you'll learn
// =================================================================================================

== What you'll learn

You will learn how to build fault-tolerant microservices in an inventory management application so that you can reduce the impact from failure and ensure continued operation of services.

You will work with an `inventory` service application, which stores information about
various JVMs that run on different systems. Whenever you make a request to the `inventory` service to retrieve
the MP Config properties of a particular host, the `inventory` service communicates with the `system` service on
that host to retrieve these properties. The `system` service then stores and returns the system properties.

You will use the `@Retry` and `@Fallback` fault tolerance annotations from the MicroProfile (MP) Fault Tolerance specification to define criteria for when to retry and when to
provide an alternative solution for a failed execution.
Fault tolerance enables the application to function even when one of its services is unavailable and makes
service invocation more resilient.

The implementation of the application and its services are provided for you.
You can find the `system` service in the `src/main/java/io/openliberty/guides/system` directory, and you can find the `inventory`
service in the `src/main/java/io/openliberty/guides/inventory` directory. If you want to learn how to
create a RESTful application, see https://openliberty.io/guides/rest-intro.html[Creating a RESTful web service].

// =================================================================================================
// Why use MicroProfile Fault Tolerance?
// =================================================================================================

=== Why use MicroProfile Fault Tolerance?

MP Fault Tolerance provides a simple and flexible solution to build fault-tolerant microservices.
Fault tolerance leverages different strategies to guide the execution and result of logic.
Retry policies, bulkheads, and circuit breakers are popular fault tolerance concepts.
They dictate whether and when executions take place, and fallbacks offer an alternative result
when an execution does not complete successfully.

MP Fault Tolerance offers the following fault tolerance policies:

* Timeout: This policy defines a duration for timeout.

* Retry: This policy defines criteria for when to retry.

* Fallback: This policy provides an alternative solution for a failed execution.

* CircuitBreaker: This policy offers a way to fail fast by automatically failing execution. It also prevents the system from
overloading and creating an indefinite wait or timeout by the clients.

* Bulkhead: This policy isolates failures in a part of the system while the rest of the system can still function.

In this guide, you will learn about the `@Retry` and `@Fallback` policies.


// =================================================================================================
// Getting Started
// =================================================================================================

include::{common-includes}/gitclone.adoc[]

// =================================================================================================
// Try what you'll build
// =================================================================================================

=== Try what you'll build

The `finish` directory in the root of this guide contains the finished fault tolerance implementation
for the application. You can try the finished application before you build your own.

To try the application, first navigate to the `finish` directory and then execute the following
Maven goals to build the application and run it inside of Open Liberty:

```
mvn clean install liberty:start-server

```

Point your browser to the `http://localhost:9080/inventory/systems/localhost` URL. You see a result in
JSON format with the system properties of your local JVM. When you visit this URL, these system properties
are automatically stored in the inventory.

Open the `finish/resource/CustomConfigSource.json` file and change the `io_openliberty_guides_system_inMaintenance` property from `false` to `true`. Then, save the file. You do not need to
restart the server. Return to your browser and point back to the
`http://localhost:9080/inventory/systems/localhost` URL. Because the `system` service is now in maintenance, you see the cached properties from the systems for this localhost.
For simplicity, only the OS name and username are stored in the cache for each host.

When you are done checking out the application, go to the `CustomConfigSource.json` file again and change the
`io_openliberty_guides_system_inMaintenance` property from `true` to `false` to set this condition back to its original value.

Run the following command to stop the Open Liberty server:

```
mvn liberty:stop-server
```

Navigate back to the `start` directory to begin.


// =================================================================================================
// Enabling fault tolerance in the application
// =================================================================================================

== Enabling fault tolerance in the application

You can find the MicroProfile Fault Tolerance API as a dependency to your `pom.xml` file. Look for the
dependancy with the `org.eclipse.microprofile.fault-tolerance` group ID.
Use this feature to build fault-tolerant microservices with the MicroProfile
Fault Tolerance API.
Also, the `mpFaultTolerance-1.0` feature is enabled in the `src/main/liberty/config/server.xml` file.


The two microservices in this application are delivered by the same server, which means that you cannot take one microservice down without the other.
To avoid taking both microservices down together, imitate the HTTP responses and exceptions that you would normally
execute when a server is down for maintenance and cannot be reached. Use MicroProfile configuration to take the server
up and down with dynamic configuration. If you want
to learn more about setting up dynamic configuration,
see https://github.com/OpenLiberty/draft-guide-microprofile-config[Configuring microservices].

To enable fault tolerance in the application, create the system client class in the
`src/main/java/io/openliberty/guides/inventory/client/SystemClient.java` file:

[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/inventory/client/SystemClient.java[tags=throw_IOException;!copyright;!javadoc]
----
This class is a client for the `system` service.

This class contains the `getPropertiesHelper()` method. This method returns a response based on whether the `system` service returns a 200 HTTP response. If the service returns a 200 HTTP response, the method returns the system properties that were
returned from the `system` service. However, if the response is anything other than 200, then a message is printed in
the terminal to explain that the response status was not acceptable. In this guide, a new `if` statement is added to the
method that checks to see if the response is a 503 response. A 503 HTTP response is returned if the
server that is called is unable to handle the request because of a temporary overload or scheduled maintenance, which
will likely be alleviated after a delay. If the response is 503, an `IOException` is thrown. This type of
exception is thrown when an input or output operation fails or is interpreted.

The public `getProperties()` method, which is used in the
`InventoryManager.java` class, calls the `getPropertiesHelper()` method. You will look into this class in more detail in the next section.

// =================================================================================================
// Adding the @Retry and @Fallback annotations
// =================================================================================================

=== Adding the @Retry and @Fallback annotations

Through the returned 503 HTTP response, the `inventory` microservice is able to recognise that the `system` microservice is
down for maintenance. As a result, the `inventory` microservice throws an IOException.
Next, set a fallback method to deal with this failure.
Create the inventory manager class in the `src/main/java/io/openliberty/guides/inventory/InventoryManager.java` file:

[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/inventory/InventoryManager.java[tags=add_retry_fallback]
----

The `@Retry` annotation dictates when and how many times the application reattempts to establish a connection
to the `system` service. In this example, the server reattempts three times.
The `@Fallback` annotation dictates which method to call when the retries are unsuccessful.
In this example, use the `fallbackForGet` method.

The `fallbackForGet()` method is the designated fallback method for the original `get()` method and checks to see if the properties variable exists in the inventory. If the properties variable is null, the application is unable to reach the `system` service to retrieve the system's properties, and the method prints out a JSON warning message in the browser. However, if
the properties variable is not null, this method returns a JSON message of the cached property values instead.


Next, create the inventory resource class in the `src/main/java/io/openliberty/guides/inventory/InventoryResource.java` file:

[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/inventory/InventoryResource.java[tags=fault_tolerance]
----

The if statement in this class now returns an error message when the `inventory` service is down for maintenance.
The if statement also calls the `get()` method in the `InventoryManager.java` class when the `inventory` service runs
as normal.


You set the application to be fault tolerant.


// =================================================================================================
// Building and running the application
// =================================================================================================

include::{common-includes}/mvnbuild.adoc[]

When the server is running, point your browser to the `http://localhost:9080/inventory/systems/localhost` URL.
You see a result in JSON format with the system properties of your local JVM.
To test the fault tolerance mechanism of your application, dynamically change
the `io_openliberty_guides_system_inMaintenance` property value to `true` in the `resource/CustomConfigSource.json` file.
Save the file, go back to your browser, and click refresh to see the cached version of the properties.
The cached system properties only have the OS name, user name key, and value pairs.

include::{common-includes}/mvnpackage.adoc[]


// =================================================================================================
// Testing the application
// =================================================================================================

== Testing the application

Although you can test your application manually, use automated tests instead because they trigger a
failure whenever a code change introduces a defect. Since the application is a RESTful web service application,
you can use JUnit and the RESTful web service client API to write tests. When you test the functionality of the
application, you test the scopes and dependencies.

Create the `FaultToleranceTest` class in the `src/test/java/it/io/openliberty/guides/faulttolerance/FaultToleranceTest.java` file:

[source, java]
----
include::finish/src/test/java/it/io/openliberty/guides/faulttolerance/FaultToleranceTest.java[tags=ft_testing;!javadoc]
----

Place the `@BeforeClass` annotation on a method that executes before any of the test cases. In this case,
the `oneTimeSetup()` method retrieves the port number for the Open Liberty server and builds a base URL string
that is used throughout the tests.

Place the `@Before` and `@After` annotations on methods that execute before and after every test case. These
methods are generally used to perform any setup and teardown tasks. In this case, the setup method creates a
JAX-RS client, which makes HTTP requests to the `inventory` service. Register this client with a
JSON-P provider (`JsrJsonpProvider`) to process JSON resources. The teardown method destroys this client
instance as well as the HTTP responses and resets the changed configuration file and the retry counter.

Break down the test cases:

* The`testFallbackForGet()` test case sends a request to the `inventory` service to get the systems properties for a
host name when the `system` service is avialable. Then, this test case puts the `system` service on maintenance. Next,
it makes a second request to the `inventory` service to return the system properties for that host name.
Lastly, it asserts whether the system properties returned from the first request were greater than the properties returned from the second time.

** In the second request, the fallback method from the `inventory` service was called to return the cached properties.
However, for the first request, the `inventory` service returned the properties from making a connection to the `system`
service.

* The `testRetryGettingSystemProperties()` test case also sends a request to the inventory service to get the system properties.
Then, it reads the retry counter in the
`/inventory/retries` endpoint to assert the endpoint with the number of retries that the test case happened to get from the
`inventory` service.

** To get the system properties, the `inventory` service retries the same number of times as stated by the `maxRetries` attribute in the
`@Retry` annotation. However, the `inventory` service makes a first call on the annotated method assuming
that the `system` service is avialable. As a result, the total calls on this method are four.

To force these test cases to execute in a particular order, put them in a `testSuite()` method and label it with
a `@Test` annotation so that it automatically executes when your test class runs.

In addition, a few endpoint tests are included for you to test the basic functionality of the `inventory` and `system` services. 
If a test failure occurs, then you might have introduced a bug into the code.

// =================================================================================================
// Running the tests
// =================================================================================================

include::{common-includes}/mvnverify.adoc[]

[source, role="no_copy"]
----
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running it.io.openliberty.guides.system.SystemEndpointTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.937 sec - in it.io.openliberty.guides.system.SystemEndpointTest
Running it.io.openliberty.guides.inventory.InventoryEndpointTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.396 sec - in it.io.openliberty.guides.inventory.InventoryEndpointTest
Running it.io.openliberty.guides.faulttolerance.FaultToleranceTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.517 sec - in it.io.openliberty.guides.faulttolerance.FaultToleranceTest

Results :

Tests run: 3, Failures: 0, Errors: 0, Skipped: 0
----

To see whether the tests detect a failure, remove the reset retries method in
the `FaultToleranceTest.java` file. Rerun the Maven build. You see a test failure occur for the
`testRetryGettingSystemProperties()` test case.

// =================================================================================================
// Great work! You're done!
// =================================================================================================

== Great work! You're done!

You built and tested a microservice application with MicroProfile fault tolerance and Open Liberty.

You can try one of the related MicroProfile guides. They demonstrate technologies that you can
learn and expand on top of what you built here.

include::{common-includes}/finish.adoc[]
